spring.application.name=sport

spring.datasource.url=jdbc:postgresql://localhost:5433/sports_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.jackson.default-property-inclusion=non_null

server.address=0.0.0.0
server.port=8080