### 16. Создаем новую единицу измерения (PUT /measure)
# Добавляем, например, килограммы
PUT http://localhost:8080/measure
Content-Type: application/json

{
  "name": "Килограмм",
  "shortName": "кг"
}

### 17. Привязываем единицу измерения к атрибуту (PUT /attribute/{id}/measure)
# Вместо "1" в ссылке подставь реальный ID атрибута (например, атрибут "Вес").
# В теле запроса передаем объект единицы измерения (укажи ID той меры, которую создал в прошлом запросе)
PUT http://localhost:8080/attribute/1/measure
Content-Type: application/json

{
  "id": 1,
  "name": "Килограмм",
  "shortName": "кг"
}

### 15. Получаем список атрибутов с их значениями для конкретного класса (GET /attribute?classId=...)
# Подставь существующий ID класса (например, 1)
GET http://localhost:8080/attribute?classId=1
Accept: application/json


### --- ПРОВЕРКА УДАЛЕНИЯ КЛАССА ---

### Удаление класса (DELETE)
# Я не вижу точного пути в твоем ClassController, поэтому написал примерный URL.
# Если у тебя маппинг другой (например, /category/class/2), поправь ссылку.
# Логика проверки:
# 1. Убедись, что в БД есть дед (ID=1), батя (ID=2) и сын (ID=3). Сын привязан к бате, батя к деду.
# 2. Удаляй батю (ID=2).
# 3. После этого чекай базу: батя должен исчезнуть, а сын (ID=3) должен перепривязаться к деду (ID=1).
DELETE http://localhost:8080/class/2